# Generated by Django 4.0.4 on 2022-05-02 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular', models.CharField(max_length=30)),
                ('children_age', models.IntegerField(max_length=2)),
                ('new_release', models.DateField(default=datetime.datetime(2022, 5, 2, 21, 39, 42, 221943, tzinfo=utc))),
            ],
        ),
    ]
