# Generated by Django 4.0.4 on 2022-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movietype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('children', 'Children'), ('new', 'New_Release')], max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], default=30, max_length=10)),
                ('popularity', models.CharField(choices=[('low', '⭐'), ('medium', '⭐,⭐'), ('high', '⭐, ⭐, ⭐')], max_length=60)),
            ],
        ),
        migrations.RenameField(
            model_name='movietype',
            old_name='regular',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='movietype',
            name='children_age',
        ),
        migrations.RemoveField(
            model_name='movietype',
            name='new_release',
        ),
    ]
